# Generated by Django 3.0.8 on 2020-12-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_hr', '0005_employee_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='leave',
            new_name='sickDays',
        ),
        migrations.AddField(
            model_name='employee',
            name='vacationDays',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='leaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacationDays', models.IntegerField(default=0)),
                ('sickDays', models.IntegerField(default=0)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected')], max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveRequests', to='django_hr.Employee')),
            ],
        ),
    ]
