# Generated by Django 3.0.8 on 2020-12-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hr', '0006_auto_20201225_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='employeeComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hrComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unpaidDays',
            field=models.IntegerField(default=0),
        ),
    ]
