# Generated by Django 3.0.8 on 2020-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hr', '0007_auto_20201225_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='sickDays',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='unpaidDays',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='vacationDays',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
