# Generated by Django 3.0.8 on 2020-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hr', '0008_auto_20201226_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leaveType',
            field=models.CharField(choices=[('PTO', 'Paid Vacation'), ('SL', 'Sick Leave'), ('UTO', 'Unpaid Time Off')], default='PTO', max_length=30),
            preserve_default=False,
        ),
    ]
