# Generated by Django 3.0.8 on 2020-12-26 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hr', '0010_auto_20201226_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
