# Generated by Django 3.0.8 on 2020-12-28 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hr', '0012_auto_20201227_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
